1.	Create a NumPy array and make a copy of it. Modify the original array and print both the original and copied arrays.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()

arr[0] = 99

print(" Modified Original array:", arr)
print("Copied array:", arr_copy)


 Modified Original array: [99  2  3  4  5]
Copied array: [1 2 3 4 5]


2.	Create a view of a NumPy array. Modify the view and print both the original and the view. How do the results compare to using a copy?

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()

arr_view[1] = 99

print("Original array:", arr)
print("View of array:", arr_view)


Original array: [ 1 99  3  4  5]
View of array: [ 1 99  3  4  5]


3.	Explain the difference between array.copy() and array.view() in NumPy. Provide an example to illustrate the difference.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()
arr_view = arr.view()

arr[2] = 99

print("Original array:", arr)
print("Copied array:", arr_copy)  # Independent
print("View of array:", arr_view)  # Reflects changes in the original


Original array: [ 1  2 99  4  5]
Copied array: [1 2 3 4 5]
View of array: [ 1  2 99  4  5]


4.	Create a 2D NumPy array and generate a view that represents only the first row. Modify this view and print the changes in both the original array and the view

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_view = arr[0, :]

row_view[1] = 99

print("Original array:\n", arr)
print("Row view:", row_view)


Original array:
 [[ 1 99  3]
 [ 4  5  6]]
Row view: [ 1 99  3]


5.	Create a NumPy array and another array by slicing the first array. Check whether the second array is a copy or a view of the first array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4]

print(arr)
print(sliced_arr)
print("-----------------------------------")
print(sliced_arr.base)
print(arr.base)



[1 2 3 4 5]
[2 3 4]
-----------------------------------
[1 2 3 4 5]
None


6.	Use the np.may_share_memory() function to check if two arrays share the same memory. Provide an example.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = arr1.view()

print(np.may_share_memory(arr1, arr2))
# may_share_memory returns True as they share memory.

True


7.	Create a NumPy array, then use the reshape() function on it. Check whether the reshaped array is a view or a copy.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)

print(np.shares_memory(arr, reshaped_arr))
# Reshaping creates a view, so shares_memory returns True.
# Or use base

print(reshaped_arr.base)


True
[1 2 3 4 5 6]


8.	Create a NumPy array and print its shape. Then reshape it to another valid shape and print the new shape.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original shape:", arr.shape)

reshaped_arr = arr.reshape(2, 3)
print("New shape:", reshaped_arr.shape)


Original shape: (6,)
New shape: (2, 3)


9.	Given a 1D array of length 12, reshape it into a 2D array with 3 rows. Then, reshape it into a 3D array. Print the shapes at each step.

In [ ]:
arr = np.arange(12)
arr_2d = arr.reshape(3, 4)
arr_3d = arr.reshape(2, 3, 2)

print("2D shape:", arr_2d.shape)
print("3D shape:", arr_3d.shape)


2D shape: (3, 4)
3D shape: (2, 3, 2)


10.	Create a 3x4 matrix and then reshape it into a 2x6 matrix. Verify if reshaping changes the data content.

In [ ]:
arr = np.arange(12).reshape(3, 4)
reshaped_arr = arr.reshape(2, 6)
print(arr)
print("Reshaped array:\n", reshaped_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


11.	Reshape a 2D array into a 3D array. Then reshape it back to its original 2D shape.

In [ ]:
arr = np.arange(12).reshape(3, 4)
reshaped_arr = arr.reshape(2, 2, 3)

print("3D reshaped array:\n", reshaped_arr)
reshaped_back = reshaped_arr.reshape(3, 4)

print("Reshaped back to 2D:\n", reshaped_back)


3D reshaped array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Reshaped back to 2D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


12.	Given a 4x4 matrix, reshape it into a 2D array with dimensions 2x8. Then, reshape it back to 4x4.

In [ ]:
arr = np.arange(16).reshape(4, 4)
reshaped_arr = arr.reshape(2, 8)

print("2x8 reshaped array:\n", reshaped_arr)
reshaped_back = reshaped_arr.reshape(4, 4)

print("Reshaped back to 4x4:\n", reshaped_back)


2x8 reshaped array:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
Reshaped back to 4x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


13.	Create a 3D array and flatten it into a 1D array using reshape(-1).

In [ ]:
arr = np.arange(12).reshape(2, 2, 3)
flattened_arr = arr.reshape(-1)

print("Flattened array:", flattened_arr)


Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


14.	Create a 3x3 matrix and iterate over its elements row by row.

In [ ]:
arr = np.arange(9).reshape(3, 3)

for row in arr:
    print("Row:", row)


Row: [0 1 2]
Row: [3 4 5]
Row: [6 7 8]


15.	Create a 2D array. Print index of each element including that element.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


16.	Iterate over a 3D array and print each element, along with its corresponding index.

In [ ]:

import numpy as np
arr = np.arange(8).reshape(2, 2, 2)
for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


17.	Create a 2D NumPy array and use np.nditer() to iterate over it. Print each element.

In [ ]:
arr = np.arange(6).reshape(2, 3)

for x in np.nditer(arr):
    print(x)


0
1
2
3
4
5


18.	Create a 3D array. Print each element and its corresponding index.

In [ ]:
arr = np.arange(8).reshape(2, 2, 2)

print(arr)
for x in np.ndenumerate(arr):
    print(x)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 1, 0), 2)
((0, 1, 1), 3)
((1, 0, 0), 4)
((1, 0, 1), 5)
((1, 1, 0), 6)
((1, 1, 1), 7)


19.	Create a 6D array and use nditer() and print each element .

In [ ]:
import numpy as np

# Create a 6D array using ndmin
arr = np.array([1, 2, 3, 4], ndmin=6)

print("6D array shape:", arr.shape)

for x in np.nditer(arr):
  print(x)


6D array shape: (1, 1, 1, 1, 1, 4)
1
2
3
4


20.	Create a 2D integer array and use nditer() to iterate over it as if it were an float array. Print the elements.

In [ ]:
import numpy as np

# Create a 2D integer array
arr = np.array([[1, 2], [3, 4]])

# Use nditer to iterate over the array as if it were a float array
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['float']):
    print(x)


1.0
2.0
3.0
4.0


21.	Use nditer() to iterate over a mixed data type array, where some elements are floats and others are integers.

In [ ]:
arr = np.array([1, 2.5, 3, 4.5])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['float']):
    print(x)


1.0
2.5
3.0
4.5


22.	Create a 1D array and iterate over it using nditer() with op_dtypes set to different types. Observe and explain the results.

In [ ]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'],op_dtypes=['float']):
    print(x)


1.0
2.0
3.0


23.	Create a 1D array of 10 elements and iterate over it using a step size of 2. Print the accessed elements.

In [ ]:
arr = np.arange(10)

for i in np.nditer(arr[::2]):
    print(i)

0
2
4
6
8


24.	Iterate over every second element of a 2D array along with indices of the elements

In [ ]:
arr = np.arange(9).reshape(3, 3)

for x in np.ndenumerate(arr[::2]):
  print(x)



((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((1, 0), 6)
((1, 1), 7)
((1, 2), 8)


25.	Create a 3D array and iterate over every second element. Print the elements accessed in each step along with indices of element.

In [ ]:
arr = np.arange(8).reshape(2, 2,2)

print(arr)
print("------------------------------")
for x in np.ndenumerate(arr[::2]):
  print(x)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
------------------------------
((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 1, 0), 2)
((0, 1, 1), 3)
