1: Create a 1D NumPy array containing the integers from 0 to 9.

In [ ]:
import numpy as np

array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


 2: Create a 2D NumPy array of shape (3, 3) with values ranging from 1 to 9.

In [ ]:
array_2d = np.arange(1, 10).reshape(3, 3)
print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


3: Create a 3x3 identity matrix using NumPy.

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4: Generate a NumPy array of 10 random numbers between 0 and 1.

In [ ]:
random_array = np.random.rand(10)
print(random_array)


[0.50682719 0.06349175 0.02536181 0.70518903 0.77672176 0.54494151
 0.85536609 0.83604661 0.58163137 0.15736465]


 5: Create an array of 10 zeros and another of 10 ones.

In [ ]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
print(zeros_array)
print(ones_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


 6: Given the array a = np.array([10, 20, 30, 40, 50]), access the third element.

In [ ]:
a = np.array([10, 20, 30, 40, 50])
third_element = a[2]
print(third_element)


30


7: Create a 4x4 matrix and access the element at the second row, third column.

In [ ]:
matrix_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])
element = matrix_4x4[1, 2]
print(element)


7


 8: Access the last element of the array a = np.array([5, 10, 15, 20, 25]).

In [ ]:
a = np.array([5, 10, 15, 20, 25])
last_element = a[-1]
print(last_element)


25


9: For the array a = np.array([1, 3, 5, 7, 9, 11]), access the elements at indices 1, 3, and 4.

In [ ]:
a = np.array([1, 3, 5, 7, 9, 11])
selected_elements = a[[1, 3, 4]]
print(selected_elements)

# Here, you are selecting specific elements from the array a using an array of indices [1, 3, 4].
# Index 1 corresponds to the second element in the array a, which is 3.
# Index 3 corresponds to the fourth element in the array a, which is 7.
# Index 4 corresponds to the fifth element in the array a, which is 9.

[3 7 9]


10: Create a 3D array of shape (2, 2, 2) and access the element at position (1, 1, 1).

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]])
element = array_3d[1, 1, 1]
print(element)


8


 11: Given the array a = np.array([2, 4, 6, 8, 10, 12]), slice it to get the first 3 elements.

In [ ]:
a = np.array([2, 4, 6, 8, 10, 12])
sliced_array = a[:3]
print(sliced_array)


[2 4 6]


 12: Create a 4x4 array and slice it to get the first two rows and last two columns.

In [ ]:
array_4x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])
sliced_array = array_4x4[:2, -2:]
print(sliced_array)


[[3 4]
 [7 8]]


13: For the array a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), slice it to get every second element.

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = a[::2]
print(sliced_array)


[0 2 4 6 8]


14: Slice the last two elements from each row of a 3x4 array.

In [ ]:
array_3x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])
sliced_array = array_3x4[:, -2:]
print(sliced_array)


[[ 3  4]
 [ 7  8]
 [11 12]]


 15: Create a 5x5 matrix and slice out the inner 3x3 matrix.

In [ ]:
matrix_5x5 = np.array([[ 1,  2,  3,  4,  5],
                       [ 6,  7,  8,  9, 10],
                       [11, 12, 13, 14, 15],
                       [16, 17, 18, 19, 20],
                       [21, 22, 23, 24, 25]])
inner_matrix = matrix_5x5[1:4, 1:4]
print(inner_matrix)


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


16: Create an array of integers from 0 to 5 and change its data type to float.

In [ ]:
int_array = np.arange(6)
float_array = int_array.astype(float)
print(float_array)


[0. 1. 2. 3. 4. 5.]


17: Create a NumPy array of shape (3, 3) with boolean values (True/False).

In [ ]:
bool_array = np.array([[True, False, True],
                       [False, True, False],
                       [True, True, False]])
print(bool_array)


[[ True False  True]
 [False  True False]
 [ True  True False]]


18: Create an array of complex numbers (e.g., [1+2j, 3+4j, 5+6j]).

In [ ]:
complex_array = np.array([1+2j, 3+4j, 5+6j])
print(complex_array)


[1.+2.j 3.+4.j 5.+6.j]


19: Given an array of strings (e.g., ["1", "2", "3"]), convert it to an array of integers.

In [ ]:
str_array = np.array(["1", "2", "3"])
int_array = str_array.astype(int)
print(int_array)


[1 2 3]


20: Create an array of float values and then convert it to an integer type.

In [ ]:
import numpy as np

# Create an array of float values
float_array = np.array([1.9, 2.5, 3.7])

# Convert the array to integer type
int_array = float_array.astype(int)

print(int_array)


[1 2 3]
